# Generated by Django 5.1.7 on 2025-11-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pet_tutor_alter_servico_tutor_alter_tutor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TUTOR', 'Tutor')], default='TUTOR', max_length=10),
        ),
    ]
