# Generated by Django 5.1.7 on 2025-11-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
    ]
