# Generated by Django 5.1.7 on 2025-08-25 16:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_obsevarçao_pet_observacao_agendamento_tutor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['data_hora'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['nome'], 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.AlterModelOptions(
            name='veterinario',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Veterinário', 'verbose_name_plural': 'Veterinários'},
        ),
        migrations.RemoveField(
            model_name='veterinario',
            name='espectalidade',
        ),
        migrations.RemoveField(
            model_name='veterinario',
            name='horario_atedimento',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='core.pet'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.servico'),
        ),
        migrations.AddField(
            model_name='pet',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='crmv',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='CRMV'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='especialidade',
            field=models.CharField(blank=True, choices=[('clinica_geral', 'Clínica Geral'), ('cirurgia', 'Cirurgia'), ('odontologia', 'Odontologia'), ('dermatologia', 'Dermatologia'), ('oftalmologia', 'Oftalmologia'), ('cardiologia', 'Cardiologia')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='horario_atendimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='telefone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='core.tutor'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='veterinario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='core.veterinario'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pet', to='core.tutor'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=45, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='endereco',
            field=models.CharField(max_length=60, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nome_completo',
            field=models.CharField(max_length=45, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
