# Generated by Django 5.1.7 on 2025-09-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_tutor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
