# Generated by Django 5.1.7 on 2025-09-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tutor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='core.pet'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servico'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='core.tutor'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='core.veterinario'),
        ),
    ]
