# Generated by Django 5.1.7 on 2025-09-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_agendamento_pet_alter_agendamento_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='tutor',
        ),
    ]
