# Generated by Django 5.1.7 on 2025-09-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_agendamento_pet_alter_agendamento_servico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='telefone',
        ),
        migrations.AddField(
            model_name='tutor',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='core.tutor'),
        ),
    ]
