# Generated by Django 5.2.6 on 2025-09-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_tutor_options_remove_pet_peso_and_more'),
        ('core', '0013_alter_pet_especie'),
    ]

    operations = [
    ]
