# Generated by Django 5.1.7 on 2025-09-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20250915_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={},
        ),
    ]
